title: 刘晋尧
url: "https://github.com/derekwin"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/derekwin"
footer_text: "my github"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Jacelau@outlook.com"
   link: "Mailto:Jacelau@outlook.com"
 - name: "17684352629"
  #  link: "resume.pdf"
#  - name: "github.com/derekwin"
#    link: "https://github.com/derekwin"
